# Generated by Django 4.2.3 on 2023-07-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_owner_pet_alter_owner_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='profile_photo',
        ),
    ]
