# Generated by Django 4.2.3 on 2023-07-10 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners', '0003_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('etc', 'Other')], max_length=20),
        ),
    ]
