# Generated by Django 4.2.3 on 2023-07-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners', '0007_alter_owner_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.AlterField(
            model_name='owner',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
