# Generated by Django 4.2.3 on 2023-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_remove_booking_pet'),
        ('owners', '0008_remove_pet_species_alter_owner_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pet',
        ),
        migrations.AddField(
            model_name='owner',
            name='neutering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_breed',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='owner',
            name='pet_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
