# Generated by Django 4.2.3 on 2023-08-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_remove_booking_owner'),
        ('owners', '0011_alter_owner_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
