# Generated by Django 4.2.3 on 2023-07-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_age_remove_user_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.pet'),
        ),
    ]
