# Generated by Django 4.2.3 on 2023-07-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
