# Generated by Django 4.2.3 on 2023-08-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0011_alter_owner_account'),
        ('users', '0008_remove_user_pet_delete_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
    ]
