# Generated by Django 4.2.3 on 2023-08-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
