# Generated by Django 4.2.3 on 2023-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='neutering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_breed',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
