# Generated by Django 4.2.3 on 2023-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_neutering_user_pet_age_user_pet_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neutering',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_breed',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pet_weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
