# Generated by Django 4.2.3 on 2023-07-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boarders', '0001_initial'),
        ('sitters', '0002_initial'),
        ('medias', '0003_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='boarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='boarders.boarder'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='sitters.sitter'),
        ),
    ]
