# Generated by Django 4.2.3 on 2023-07-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoarderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarder_name', models.CharField(max_length=80)),
                ('boarder_country', models.CharField(default='Ireland', max_length=50)),
                ('boarder_city', models.CharField(default='Dublin', max_length=80)),
                ('boarder_price', models.PositiveIntegerField()),
                ('boarder_address', models.CharField(default='', max_length=200)),
                ('boarder_description', models.TextField(default='')),
                ('boarder_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarders', to='categories.category')),
                ('boarder_services', models.ManyToManyField(to='boarders.boarderservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
