# Generated by Django 4.2.3 on 2023-07-12 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boarders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='boarder_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='boarders', to=settings.AUTH_USER_MODEL),
        ),
    ]
