# Generated by Django 4.2.3 on 2023-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
