# Generated by Django 4.2.3 on 2023-07-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0003_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
