# Generated by Django 4.2.3 on 2023-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='neutralization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
