# Generated by Django 4.2.3 on 2023-07-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_description_booking_neutralization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='neutralization',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet_name',
        ),
    ]
