# Generated by Django 4.2.3 on 2023-07-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pet'),
        ('bookings', '0007_booking_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pet'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
