# Generated by Django 4.2.3 on 2023-07-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_pet_delete_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
    ]
