# Generated by Django 4.2.3 on 2023-07-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_remove_owner_profile_photo'),
        ('bookings', '0009_remove_booking_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='owners.owner'),
        ),
    ]
