# Generated by Django 4.2.3 on 2023-07-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
    ]
