# Generated by Django 4.2.3 on 2023-08-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_remove_booking_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
    ]
